Controllers/RegistrationController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Application2.Models;
using Microsoft.AspNetCore.Authorization;
using db;
using System.Net.Mail;
using Microsoft.AspNetCore.Identity;
namespace Application2.Controllers;
[ApiController]
[Route("[controller]")]
public class RegistrationController:Controller{
    private  Context _DB;
    public RegistrationController(Context DB)
    {
        _DB = DB;
    }
    [Route("Regist")]
    public IActionResult Regist(){
        return View();
    }
    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    [Route("Regist")]
    
    public async Task<IActionResult> Regist([FromForm] User user){
       
       
        if (ModelState.IsValid)
        {
            if(!(_DB.Users.Any(c=>c.Telephone == user.Telephone) | _DB.Users.Any(c=>c.Email == user.Email))){
                if(user.role == "Person"){
                    user.DirectoryPhotoUser = "/home/user/Source/test_drive/Application2/wwwroot/img/no_avatar.webp";
                    await _DB.Users.AddAsync(user);
                    await _DB.SaveChangesAsync();
                    Person person = new Person(){Id=user.Id, NickName=user.NickName, Password=user.Password, Email=user.Email, Telephone=user.Telephone, DirectoryPhotoUser = "/home/user/Source/test_drive/Application2/wwwroot/img/no_avatar.webp"};
                    await _DB.Persons.AddAsync(person);
                    await _DB.SaveChangesAsync();
                }
                else{
                    user.DirectoryPhotoUser = "/home/user/Source/test_drive/Application2/wwwroot/img/no_avatar.webp";
                    await _DB.Users.AddAsync(user);
                    await _DB.SaveChangesAsync();
                    Seller seller = new Seller(){Id=user.Id, NickName=user.NickName, Password=user.Password, Email=user.Email, Telephone=user.Telephone, CountMoney=0, DirectoryPhotoUser=user.DirectoryPhotoUser};
                    await _DB.Sellers.AddAsync(seller);
                    await _DB.SaveChangesAsync();
                }
                
                return RedirectToRoute(new { controller="Home", action="Index"});
            }
            else{
                ViewData["ErrorMessage"]= "Такой пользователь уже существует";
                return View();
            }
            
        }
        ViewData["ErrorMessage"]= "Ошибка авторизации попробуйте еще раз";
        return View();
        
    }
}

Controllers/VhodController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Application2.Models;
using Microsoft.AspNetCore.Authorization;
using db;
using System.Net.Mail;
using Microsoft.AspNetCore.Identity;
using localstorage;
using System.Web;
namespace Application2.Controllers;

using System.Net;
using DATA;
using Manager;
[ApiController]
[Route("[controller]")]
public class VhodController:Controller{
    private  Context _DB;
    public VhodController(Context DB)
    {
        _DB = DB;
    }
    [Route("Regist")]
    public IActionResult Vhod(){

        return View();
    }
    [HttpPost]
    [Route("Regist")]
    public async Task<IActionResult> Vhod([FromForm]  Manager.ManagerUsers user){

        User User = _DB.Users.FirstOrDefault(c=>c.Email == user.Email);
        if(User!=null){
            if(User.Password == user.Password){
                CookieOptions options = new(){Domain = "localhost", Expires = DateTime.Now.AddYears(1), Path = "/"};
                HttpContext.Response.Cookies.Append("id", Convert.ToString(User.Id), options);
                HttpContext.Response.Cookies.Append("role", User.role, options);
                return RedirectToRoute(new{ controller="Home", action="Index"});
            }
            else{
                ViewData["ErrorMesage"]= "Неверный Пароль";
                return View();
            }
        } 
        else{
            ViewData["ErrorMesage"]= "Неверный Email";
            return View();
    
        }

        
    }

    
}

Views/Shared/_Layout.cshtml
@using Application2.DATA;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Application</title>
    <link rel="stylesheet" href="/home/user/Source/test_drive/Application2/wwwroot/css/Layout.css">
    <link rel="stylesheet" href="/home/user/Source/test_drive/Application2/wwwroot/css/Home.css">
    <link rel="stylesheet" href="/home/user/Source/test_drive/Application2/wwwroot/css/Accaunt.css">
    <link rel="stylesheet" href="/home/user/Source/test_drive/Application2/wwwroot/css/regist.css">
    <link rel="stylesheet" href="/home/user/Source/test_drive/Application2/wwwroot/css/regist_tovar.css">
    <script src="/home/user/Source/test_drive/Application2/wwwroot/js/site.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.js" type="text/javascript"></script>
</head>
<body>
    <header>
        <nav >
            <div class="logo">
                    <a  asp-area="" asp-controller="Home" asp-action="Index">logo</a>
            </div>    
            <div class="nav_div">
                <ul class="menu" >
                    <li >
                        <a  asp-area="" asp-controller="Home" asp-action="Index"><span class="span">Home</span></a>
                    </li>
                    @if(data.ID == "0"){
                        <li >
                            <a  asp-controller="Registration" asp-action="Regist"><span class="span">Rigister</span></a>
                        </li>
                        <li >
                            <a  asp-controller="Vhod" asp-action="Vhod"><span class="span">Vhod</span></a>
                        </li>
                    }
                    else{
                        @if(data.role == "Person"){
                            <li >
                                <a  asp-controller="Accaunt" asp-action="Cart"><img class="znachok" src="/home/user/Source/test_drive/Application2/wwwroot/img/app_img/корзина.png" alt=""></a>
                            </li>
                        }
                        else{
                            <li >
                                <a  asp-controller="Accaunt" asp-action="ListProducts"><img class="znachok" src="/home/user/Source/test_drive/Application2/wwwroot/img/app_img/корзина.png" alt=""></a>
                            </li>
                        }
                        
                    }
                
                    <li>
                        <a  asp-controller="Accaunt" asp-action="Accaunt"><img class="znachok" src="/home/user/Source/test_drive/Application2/wwwroot/img/app_img/accaunt.png" ></a>
                    </li>
                
                </ul>
            </div>
        </nav>
    </header>
    <main class="main">
        @RenderBody()
    </main>
    
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>